name: curcap
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - backports.zstd=1.2.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - contourpy=1.3.3
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - fonttools=4.61.0
  - freetype=2.14.1
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcxx=21.1.7
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libntlm=1.8
  - libopenblas=0.3.30
  - libpng=1.6.53
  - libpq=18.1
  - libsqlite=3.51.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.7
  - lxml=6.0.2
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - munkres=1.1.4
  - ncurses=6.5
  - numpy=2.3.5
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - pillow=12.0.0
  - pip=25.3
  - psycopg=3.3.2
  - psycopg-c=3.3.2
  - pthread-stubs=0.4
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - qhull=2020.2
  - readline=8.2
  - requests=2.32.5
  - setuptools=80.9.0
  - six=1.17.0
  - tk=8.6.13
  - tornado=6.5.2
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - urllib3=2.6.1
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zlib-ng=2.3.2
  - zstd=1.5.7
prefix: /opt/miniconda3/envs/curcap
